export const FETCHING_BOOKING_DATA = 'FETCHING_BOOKING_DATA'
export const FETCHING_BOOKING_DATA_SUCCESS = 'FETCHING_BOOKING_DATA_SUCCESS'
export const FETCHING_BOOKING_DATA_FAIL = 'FETCHING_BOOKING_DATA_FAIL'
// CANCEL_BOOKING
export const CANCEL_BOOKING = 'CANCEL_BOOKING'
// Questions
export const FETCHING_QUESTION_DATA = 'FETCHING_QUESTION_DATA'
export const FETCHING_QUESTION_DATA_SUCCESS = 'FETCHING_QUESTION_DATA_SUCCESS'
export const FETCHING_QUESTION_DATA_FAIL = 'FETCHING_QUESTION_DATA_FAIL'
// Answers
export const FETCHING_ANSWER_DATA = 'FETCHING_ANSWER_DATA'
export const FETCHING_ANSWER_DATA_SUCCESS = 'FETCHING_ANSWER_DATA_SUCCESS'
export const FETCHING_ANSWER_DATA_FAIL = 'FETCHING_ANSWER_DATA_FAIL'
// Accept-quote
export const POST_ACCEPT_QUOTE = 'POST_ACCEPT_QUOTE'
export const POST_ACCEPT_QUOTE_SUCCESS = 'POST_ACCEPT_QUOTE_SUCCESS'
export const POST_ACCEPT_QUOTE_FAIL = 'POST_ACCEPT_QUOTE_FAIL'
// Delete-Card
export const DELETE_CART = 'DELETE_CART'
export const DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS'
export const DELETE_CART_FAIL = 'DELETE_CART_FAIL'
// Create-Card
export const POST_CREATE_CART = 'POST_CREATE_CART'
export const POST_CREATE_CART_SUCCESS = 'POST_CREATE_CART_SUCCESS'
export const POST_CREATE_CART_FAIL = 'POST_CREATE_CART_FAIL'
// Time-Address
export const PUT_TIME_ADDRESS = 'PUT_TIME_ADDRESS'
export const PUT_TIME_ADDRESS_SUCCESS = 'PUT_TIME_ADDRESS_SUCCESS'
export const PUT_TIME_ADDRESS_FAIL = 'PUT_TIME_ADDRESS_FAIL'
export const SELECTED_DATE_TIME = 'SELECTED_DATE_TIME'
// Get Quote for cart
export const GET_QUOTES_CART = 'GET_QUOTES_CART'
export const GET_QUOTES_CART_SUCCESS = 'GET_QUOTES_CART_SUCCESS'
export const GET_QUOTES_CART_FAIL = 'GET_QUOTES_CART_FAIL'
// PUT confirm cart
export const PUT_CONFIRM_CART = 'PUT_CONFIRM_CART'
export const PUT_CONFIRM_CART_SUCCESS = 'PUT_CONFIRM_CART_SUCCESS'
export const PUT_CONFIRM_CART_FAIL = 'PUT_CONFIRM_CART_FAIL'

// RESTfull api to get all services
export const GET_ALL_SERVICES = 'GET_ALL_SERVICES'
export const GET_ALL_SERVICES_SUCCESS = 'GET_ALL_SERVICES_SUCCESS'
export const GET_ALL_SERVICES_FAIL = 'GET_ALL_SERVICES_FAIL'
export const SELECTED_SERVICE = 'SELECTED_SERVICE'
export const FILTER_SERVICES = 'FILTER_SERVICES'

// promotion
export const POST_PROMOTION = 'POST_PROMOTION'
export const POST_PROMOTION_SUCCESS = 'POST_PROMOTION_SUCCESS'
export const POST_PROMOTION_FAIL = 'POST_PROMOTION_FAIL'
// provider profile
export const GET_PROFILE_PROVIDER = 'GET_PROFILE_PROVIDER'
export const GET_PROFILE_PROVIDER_SUCCESS = 'GET_PROFILE_PROVIDER_SUCCESS'
export const GET_PROFILE_PROVIDER_FAIL = 'GET_PROFILE_PROVIDER_FAIL'
// user rating
export const GET_USER_RATING = 'GET_USER_RATING'
export const GET_USER_RATING_SUCCESS = 'GET_USER_RATING_SUCCESS'
export const GET_USER_RATING_FAIL = 'GET_USER_RATING_FAIL'
// Next Question
export const SET_NEXT_QUESTION = 'SET_NEXT_QUESTION'
export const SET_NEXT_QUESTION_SUCCESS = 'SET_NEXT_QUESTION_SUCCESS'
export const SET_NEXT_QUESTION_FAIL = 'SET_NEXT_QUESTION_FAIL'
export const SET_LIST_QUESTION_TEXT = 'SET_LIST_QUESTION_TEXT'

// CART
export const SET_AUTO_ASSIGN = 'SET_AUTO_ASSIGN'
export const SET_CART_DETAIL = 'SET_CART_DETAIL'
export const SET_COMMENT = 'SET_COMMENT'
export const SET_CURRENCY_CODE = 'SET_CURRENCY_CODE'
export const SET_INFO = 'SET_INFO'
export const SET_IS_PACK = 'SET_IS_PACK'
export const SET_PACK_CODE = 'SET_PACK_CODE'
export const SET_PAYMENT_METHOD = 'SET_PAYMENT_METHOD'
export const SET_REGION_CODE = 'SET_REGION_CODE'
export const SET_USER_KEY = 'SET_USER_KEY'
